name: Publier une nouvelle version

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Création de la release
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      # --- MODIFICATION IMPORTANTE ICI ---
      # On force le nom du fichier zip à être 'abcupdater.zip'
      - name: Créer l'archive du plugin avec le nom correct
        run: zip -r abcupdater.zip . -x ".git/*" ".github/*"

      - name: Créer la Release GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # --- MODIFICATION IMPORTANTE ICI ---
          # On dit au robot de chercher un fichier nommé 'abcupdater.zip' pour l'attacher
          artifacts: "abcupdater.zip"
          generateReleaseNotes: true