# Nom du workflow
name: Créer et Publier le Plugin

on:
  push:
    tags:
      - 'v*'
      - 'V.*'

jobs:
  build-and-release:
    name: Création de la Release
    runs-on: ubuntu-latest

    # --- L'AJOUT QUI VA TOUT RÉSOUDRE ---
    # Donne explicitement la permission au robot d'écrire (créer) des releases.
    permissions:
      contents: write
    # ------------------------------------

    steps:
      # Étape 1: Récupère le code source
      - name: Récupération du code
        uses: actions/checkout@v4

      # Étape 2: Crée l'archive ZIP avec le nom EXACT "abcupdater.zip"
      - name: Créer l'archive 'abcupdater.zip'
        run: zip -r abcupdater.zip . -x ".git/*" ".github/*"

      # Étape 3: Crée la Release sur GitHub et attache notre fichier ZIP personnalisé
      - name: Créer la Release et attacher l'archive
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "abcupdater.zip"
          generateReleaseNotes: true
          allowUpdates: true # FIX: Allow updating an existing release to prevent "already_exists" error
